### ISSUE TITLE
truffle compile error

### ISSUE THREAD

**Issue by duncanwang** [blockchain-technical-practice/eth-weibo#1]
How to  solve this error ?

duncanwang@ubuntu:~/work/eth-weibo-master$ truffle compile
Error: Cannot find module 'truffle-default-builder'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/duncanwang/work/eth-weibo-master/truffle.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

**Comment by gcc2ge** [comment]
please change truffle version to v3.4.11
